class PIPE_MSG_TYPE:
    COND_TYPE = 0
    GEP_TYPE = 1
    MEMCMP_TYPE = 2
    ADD_CONSTRAINT_TYPE = 3
    MERRO_TYPE = 4
    EXIT_TYPE = 5
    LOOP_TYPE = 6
    BB_TYPE = 7
    EVENT_TYPE = 8
    GV_TYPE = 9  # Global Variable
    MINIMIZE_TYPE = 10

class PIPE_EVENT_TYPE:
    EVENT_LAZY_INIT = 100
    EVENT_USAGE_CITE = 101
    EVENT_EXTENSION = 102
    EVENT_ASSERTION = 103
    EVENT_TYPE_BIND = 104
    EVENT_COPY_OVERFLOW = 105

    EVENT_UBI = 150
    EVENT_UAF = 151
    EVENT_OOB = 152
    EVENT_NULL_DEREF = 153
    EVENT_PANIC = 171

    TRACE_BB = 200

class MEMERR_FLAGS:
    UAF  = 0x1
    OLB  = 0x2
    OUB  = 0x4
    UBI  = 0x8
    NULL = 0x10
    FREE = 0x20

MEMERR_TO_EVENT = {
    MEMERR_FLAGS.UAF:  PIPE_EVENT_TYPE.EVENT_UAF,
    MEMERR_FLAGS.OLB:  PIPE_EVENT_TYPE.EVENT_OOB,
    MEMERR_FLAGS.OUB:  PIPE_EVENT_TYPE.EVENT_OOB,
    MEMERR_FLAGS.UBI:  PIPE_EVENT_TYPE.EVENT_UBI,
    MEMERR_FLAGS.NULL: PIPE_EVENT_TYPE.EVENT_NULL_DEREF,
}

class COND_FLAGS:
    ADD_CONS = 1
    LOOP_EXIT = 2
    LOOP_LATCH = 4
