"""Plan-driven scheduler for contract-guided concolic execution.

Consumes a trace plan JSON (generated by LLM from annotated source + contracts)
that specifies which BB IDs to target, their priority, and which BBs to
deprioritize (e.g., loop back-edges).

Plan JSON format:
{
  "function": "adler32_z",
  "traces": [
    {
      "goal": "buf: not_null when len=1",
      "target_bids": [100000],
      "priority": 1
    },
    ...
  ],
  "deprioritize": [
    {"bb_id": 100005, "reason": "loop back-edge"},
    ...
  ]
}

Scheduling strategy:
  1. target_bids are branch IDs (= BB IDs containing the conditional) to flip
  2. Coverage tracked via bid in append(): when SymSan flips a target branch
     (COND_TYPE), that target is covered
  3. Infeasibility: if a target BB is visited (BB_TYPE) but its branch is never
     symbolic (no COND_TYPE), it can't be flipped → infeasible
  4. Classify new seeds into priority queues:
     - target_queue: seed flips a target branch
     - explore_queue: seed from a new branch ID
     - path_queue: everything else (bounded)
  5. Drain queues by priority (target > explore > path)
  6. Terminate when all targets covered, all remaining infeasible, queues
     exhausted, or budget exceeded
"""

import json
import logging
import pickle
from time import time
from typing import List

from control import UcsanTicket  # type: ignore
from .base import SchedulerBase
from .seed import Seed

logger = logging.getLogger(__name__)


class PolicyScheduler(SchedulerBase):
    def __init__(self, plan_path: str, save_seeds: bool = False) -> None:
        super().__init__()
        with open(plan_path) as f:
            self._plan = json.load(f)

        # Parse traces sorted by priority (lower number = higher priority)
        self._traces = []
        for t in self._plan.get("traces", []):
            bids = set(t.get("target_bids", []))
            bridge_bids = set(t.get("bridge_bids", []))
            self._traces.append({
                "goal": t.get("goal", ""),
                "description": t.get("description", ""),
                "target_bids": bids,
                "bridge_bids": bridge_bids,
                "ordered_bridge_bids": [
                    int(v) for v in t.get("ordered_bridge_bids", [])
                ],
                "priority": t.get("priority", 1),
            })
        self._traces.sort(key=lambda t: t["priority"])

        # Collect all target BBs across all traces
        self._all_target_bbs: set[int] = set()
        self._target_order: list[int] = []
        for t in self._traces:
            for bid in sorted(t["target_bids"]):
                self._all_target_bbs.add(bid)
                if bid not in self._target_order:
                    self._target_order.append(bid)

        # Loop-related policy targets may need more than one flip attempt, but
        # unbounded retries recreate loop path explosion. Cap them per target.
        self._loop_target_retry_limit = int(self._plan.get("loop_target_retry", 16))
        self._loop_target_retry_count: dict[int, int] = {}
        self._target_retry_limit = int(self._plan.get("target_retry", 16))
        self._target_retry_count: dict[int, int] = {}
        self._force_target_solve_limit = int(
            self._plan.get("force_target_solve", 64)
        )
        self._force_target_solve_count: dict[int, int] = {}
        self._force_desired_branches = bool(
            self._plan.get("force_desired_branches", False)
        )
        self._contextual_targets = bool(self._plan.get("contextual_targets", False))
        self._contextual_lookahead = max(
            1, int(self._plan.get("contextual_lookahead", 1))
        )
        self._drop_non_policy_after_bridge = bool(
            self._plan.get("drop_non_policy_after_bridge", False)
        )
        self._drop_non_policy_min_bridge = int(
            self._plan.get("drop_non_policy_min_bridge", 0)
        )
        self._advanced_bridge_min_priority = int(
            self._plan.get("advanced_bridge_min_priority", 0)
        )
        self._advanced_bridge_retry_limit = int(
            self._plan.get("advanced_bridge_retry", 128)
        )
        self._advanced_bridge_retry_count: dict[int, int] = {}
        self._path_queue_limit = int(self._plan.get("path_queue_limit", 0))
        self._drain_after_covered = bool(
            self._plan.get("drain_after_covered", False)
        )
        self._support_bids_after_bridge = []
        self._support_bid_retry_limit = int(
            self._plan.get("support_bid_retry", 64)
        )
        self._support_bid_retry_count: dict[tuple[int, int], int] = {}
        for item in self._plan.get("support_bids_after_bridge", []):
            try:
                self._support_bids_after_bridge.append({
                    "min_bridge": int(item.get("min_bridge", 0)),
                    "bids": set(int(v) for v in item.get("bids", [])),
                    "reason": item.get("reason", ""),
                })
            except (TypeError, ValueError):
                logger.warning(
                    f"[Plan] Ignoring malformed support-bid rule: {item}"
                )
        self._loop_threshold_overrides = []
        self._loop_termination_overrides = []
        self._active_loop_threshold = 0
        for item in self._plan.get("loop_threshold_overrides", []):
            try:
                self._loop_threshold_overrides.append({
                    "after_bbs": set(int(v) for v in item.get("after_bbs", [])),
                    "threshold": int(item["threshold"]),
                    "reason": item.get("reason", ""),
                })
            except (KeyError, TypeError, ValueError):
                logger.warning(f"[Plan] Ignoring malformed loop override: {item}")
        for item in self._plan.get("loop_termination_overrides", []):
            try:
                self._loop_termination_overrides.append({
                    "after_bbs": set(int(v) for v in item.get("after_bbs", [])),
                    "loop_bids": set(int(v) for v in item.get("loop_bids", [])),
                    "reason": item.get("reason", ""),
                })
            except (TypeError, ValueError):
                logger.warning(
                    f"[Plan] Ignoring malformed loop termination override: {item}"
                )

        # Hard same-execution prefix constraints.  These prevent late target
        # states from flooding the queues when they skipped required setup BBs
        # such as the allocation that must dominate a later checked access.
        self._must_prefix_rules = []
        self._must_prefix_drop_count = 0
        self._must_prefix_drop_by_rule: dict[str, int] = {}
        self._must_prefix_abort_count = 0
        self._current_prefix_abort_rule = None
        for idx, item in enumerate(self._plan.get("must_prefix", [])):
            try:
                name = item.get("name", f"rule_{idx}")
                action = item.get("action", "discard")
                if action not in ("discard", "abort"):
                    logger.warning(
                        f"[Plan] Unsupported must_prefix action {action!r}; "
                        "using 'discard'"
                    )
                    action = "discard"
                self._must_prefix_rules.append({
                    "name": name,
                    "required_bbs": set(int(v) for v in item["required_bbs"]),
                    "before_bbs": set(int(v) for v in item["before_bbs"]),
                    "action": action,
                })
                self._must_prefix_drop_by_rule[name] = 0
            except (KeyError, TypeError, ValueError):
                logger.warning(f"[Plan] Ignoring malformed must_prefix rule: {item}")

        # Deprioritized BBs (loop back-edges, etc.)
        self._depri_bbs: set[int] = {
            d["bb_id"] for d in self._plan.get("deprioritize", [])
        }
        self._direct_bids: set[int] = {
            int(v) for v in self._plan.get("direct_bids", [])
        }

        # Optional directed branch goals.  A normal target says "flip this
        # branch"; a directed target says "queue only flips that should produce
        # this runtime result on replay".  This is useful for relation gates
        # such as min(a,b), where only one side extends the exploit trace.
        self._desired_results: dict[int, int] = {}
        self._desired_addrs: dict[int, set[int]] = {}
        for item in self._plan.get("desired_branches", []):
            try:
                bid = int(item["bb_id"])
                self._desired_results[bid] = int(item["desired_result"])
                addrs = item.get("addrs", item.get("addresses", []))
                if addrs:
                    self._desired_addrs[bid] = set(int(v) for v in addrs)
            except (KeyError, TypeError, ValueError):
                logger.warning(f"[Plan] Ignoring malformed desired branch: {item}")
        self._staged_desired_branches: dict[int, list[dict]] = {}
        for item in self._plan.get("staged_desired_branches", []):
            try:
                bid = int(item["bb_id"])
                default_result = int(item["desired_result"])
                stages = []
                for stage in item.get("stages", []):
                    stages.append({
                        "desired_result": int(
                            stage.get("desired_result", default_result)
                        ),
                        "addrs": set(
                            int(v) for v in stage.get(
                                "addrs", stage.get("addresses", [])
                            )
                        ),
                        "value": (
                            int(stage["value"])
                            if "value" in stage else None
                        ),
                        "after_ordered": [
                            int(v) for v in stage.get("after_ordered", [])
                        ],
                        "name": stage.get("name", ""),
                    })
                if stages:
                    self._staged_desired_branches[bid] = stages
            except (KeyError, TypeError, ValueError):
                logger.warning(
                    f"[Plan] Ignoring malformed staged desired branch: {item}"
                )

        # Global BB coverage (persists across all seed executions)
        self._covered_bbs: set[int] = set()

        # Per-seed execution trace (reset on each new seed).  Keep both a set
        # and order so policy can distinguish aggregate coverage from a single
        # execution that actually passed through required bridge BBs.
        self._current_trace: set[int] = set()
        self._current_trace_order: list[int] = []
        self._last_bb_id: int | None = None
        self._current_branch_results: dict[int, set[int]] = {}
        self._best_bridge_progress = 0
        # Bridge progress is confirmed only by replayed BB traces.  Branch
        # flips are candidates; the replay must actually preserve/extend the
        # ordered bridge before we treat the corresponding policy stage as
        # covered.
        self._confirmed_bridge_progress = 0
        self._bridge_retry_limit = int(self._plan.get("bridge_retry", 128))
        self._bridge_retry_count: dict[int, int] = {}
        self._confirm_targets_by_replay = bool(
            self._plan.get("confirm_targets_by_replay", False)
        )

        # Track which target BBs have been visited (BB_TYPE) but not flipped (COND_TYPE)
        self._visited_target_bbs: set[int] = set()

        # Priority queues
        self._direct_queue: List[Seed] = []
        self._target_queue: List[Seed] = []
        self._explore_queue: List[Seed] = []
        self._path_queue: List[Seed] = []

        self._seen_bids: set[int] = set()
        self._seeds_hash: set[str] = set()
        self._counter = 0
        self._budget = self._plan.get("seed_budget", 500)
        self._starttime = time()
        self._save_seeds = save_seeds
        self._current_seed = Seed()

        logger.info(
            f"[Plan] Loaded: {len(self._traces)} traces, "
                f"{len(self._all_target_bbs)} target BBs, "
                f"{len(self._depri_bbs)} deprioritized BBs, "
                f"{len(self._desired_results)} directed branch goals, "
                f"{len(self._staged_desired_branches)} staged branch goals, "
                f"{len(self._support_bids_after_bridge)} support-bid rules, "
                f"{len(self._loop_threshold_overrides)} loop threshold overrides, "
                f"{len(self._loop_termination_overrides)} loop termination overrides, "
                f"{len(self._must_prefix_rules)} must-prefix rules, "
                f"budget={self._budget}"
        )
        for t in self._traces:
            logger.info(
                f"[Plan]   P{t['priority']}: {t['goal']} "
                f"(bids={sorted(t['target_bids'])}, "
                f"bridge={sorted(t['bridge_bids'])}, "
                f"ordered={t['ordered_bridge_bids']})"
            )
        for rule in self._must_prefix_rules:
            logger.info(
                f"[Plan]   must-prefix {rule['name']}: "
                f"required={sorted(rule['required_bbs'])} "
                f"before={sorted(rule['before_bbs'])}"
            )

    # ------------------------------------------------------------------
    # BB trace interface — called by manager on each BB_TYPE message
    # ------------------------------------------------------------------

    def trace_bb(self, func_id: int, bb_id: int) -> None:
        """Record a BB visit during current seed execution."""
        violated_rule = self._violated_must_prefix_for_bb(bb_id)
        if violated_rule is not None and violated_rule["action"] == "abort":
            if self._current_prefix_abort_rule is None:
                self._current_prefix_abort_rule = violated_rule
                logger.info(
                    f"[Plan] Abort current seed before BB {bb_id} "
                    f"(must-prefix {violated_rule['name']}: "
                    f"required={sorted(violated_rule['required_bbs'])}, "
                    f"before={sorted(violated_rule['before_bbs'])}, "
                    f"trace={sorted(self._current_trace)})"
                )
            return

        if bb_id not in self._current_trace:
            self._current_trace_order.append(bb_id)
        self._last_bb_id = int(bb_id)
        self._current_trace.add(bb_id)
        if bb_id in self._all_target_bbs:
            self._visited_target_bbs.add(bb_id)
        self._confirm_replayed_bridge_progress()
        if self._current_prefix_abort_rule is None:
            violated_rule = self._violated_must_prefix()
            if violated_rule is not None and violated_rule["action"] == "abort":
                self._current_prefix_abort_rule = violated_rule

    def trace_branch(self, bid: int, result: int, addr=None, context=None) -> None:
        """Record a branch outcome during current seed execution."""
        self._current_branch_results.setdefault(int(bid), set()).add(int(result))
        self._confirm_replayed_bridge_progress()

    def current_bb_id(self) -> int | None:
        """Return the most recent BB in the current execution."""
        return self._last_bb_id

    def _branch_goal_replayed(self, bid: int) -> bool:
        """Return true when this run observed the requested directed outcome."""
        desired_result, _ = self._active_desired_branch_goal(bid)
        if desired_result is None:
            return True
        return int(desired_result) in self._current_branch_results.get(bid, set())

    def _confirm_replayed_bridge_progress(self) -> None:
        """Mark policy stages covered only after their bridge replays.

        This keeps a generated flip from prematurely closing a milestone when
        the child seed later falls into a different suffix.  It is especially
        important for branch BBs whose BB is visited before the branch outcome
        is known.
        """
        score, completed = self._bridge_progress()
        if score <= self._confirmed_bridge_progress:
            return

        newly_confirmed: list[int] = []
        for t in self._traces:
            priority = int(t["priority"])
            if priority not in completed:
                continue
            for bid in t["target_bids"]:
                if not self._branch_goal_replayed(bid):
                    continue
                if bid not in self._covered_bbs:
                    self._covered_bbs.add(bid)
                    newly_confirmed.append(bid)

        self._confirmed_bridge_progress = score
        if newly_confirmed:
            logger.critical(
                "[Plan] Replay-confirmed bridge %s; covered targets %s "
                "(%s/%s)",
                score,
                sorted(newly_confirmed),
                len(self._covered_bbs),
                len(self._all_target_bbs),
            )

    def should_abort_current_trace(self) -> bool:
        """Return true when current execution violated an aborting prefix rule."""
        if self._current_prefix_abort_rule is None:
            return False
        rule = self._current_prefix_abort_rule
        self._must_prefix_abort_count += 1
        logger.info(
            f"[Plan] Abort current seed (must-prefix {rule['name']}: "
            f"required={sorted(rule['required_bbs'])}, "
            f"before={sorted(rule['before_bbs'])}, "
            f"trace={sorted(self._current_trace)})"
        )
        self._current_prefix_abort_rule = None
        return True

    def loop_threshold_for_current_trace(self) -> int | None:
        """Return a policy-requested loop threshold for the current execution.

        This lets late-stage traces keep running after they have proven they
        reached a useful bridge, without globally increasing loop work for all
        parser states.
        """
        best = self._active_loop_threshold
        best_reason = ""
        for item in self._loop_threshold_overrides:
            required = item["after_bbs"]
            if required and required.issubset(self._current_trace):
                if item["threshold"] > best:
                    best = item["threshold"]
                    best_reason = item["reason"]
        if best > self._active_loop_threshold:
            self._active_loop_threshold = best
            logger.critical(
                "[Plan] Loop threshold override -> %s after BBs %s%s",
                best,
                sorted(self._current_trace),
                f" ({best_reason})" if best_reason else "",
            )
            return best
        return None

    def should_disable_loop_termination(self, bid: int) -> bool:
        """Return true when policy wants this loop gate ignored in this trace.

        This is narrower than global loop.skip_solve: the normal loop limiter
        stays active until a trace proves it reached the requested prefix.
        """
        for item in self._loop_termination_overrides:
            loop_bids = item["loop_bids"]
            if loop_bids and bid not in loop_bids:
                continue
            required = item["after_bbs"]
            if required and not required.issubset(self._current_trace):
                continue
            reason = item["reason"]
            logger.critical(
                "[Plan] Disable loop termination for bid=%s after BBs %s%s",
                bid,
                sorted(self._current_trace),
                f" ({reason})" if reason else "",
            )
            return True
        return False

    def is_target_bid(self, bid: int) -> bool:
        """Return true when a conditional branch ID is an explicit policy target."""
        return bid in self._all_target_bbs

    def is_uncovered_target_bid(self, bid: int) -> bool:
        """Return true when a branch ID is a policy target that still needs a flip."""
        return bid in self._all_target_bbs and bid not in self._covered_bbs

    def _is_support_bid_after_bridge(self, bid: int, bridge_score: int) -> bool:
        """Keep selected data-dependency branches after a bridge is reached."""
        for item in self._support_bids_after_bridge:
            if bridge_score < item["min_bridge"]:
                continue
            if bid not in item["bids"]:
                continue
            key = (bridge_score, bid)
            count = self._support_bid_retry_count.get(key, 0)
            if count >= self._support_bid_retry_limit:
                return False
            self._support_bid_retry_count[key] = count + 1
            reason = item["reason"]
            logger.debug(
                "[Plan] Support bid %s allowed after bridge %s%s",
                bid,
                bridge_score,
                f" ({reason})" if reason else "",
            )
            return True
        return False

    def should_solve_policy_loop_target(self, bid: int, result=None) -> bool:
        """Return true when loop suppression should be bypassed for a target bid."""
        if bid not in self._all_target_bbs:
            return False
        if not self._needs_directed_solve(bid, result):
            return False
        if bid not in self._covered_bbs:
            return True

        # Once a later policy target is reached, the earlier loop gate has done
        # its job. Do not keep solving it.
        try:
            pos = self._target_order.index(bid)
        except ValueError:
            return False
        later_targets = set(self._target_order[pos + 1:])
        if later_targets & (self._covered_bbs | self._visited_target_bbs):
            return False

        count = self._loop_target_retry_count.get(bid, 0)
        if count >= self._loop_target_retry_limit:
            return False
        self._loop_target_retry_count[bid] = count + 1
        return True

    def should_force_solve_policy_target(self, bid: int, result=None, addr=None) -> bool:
        """Return true when a policy target should be solved in this prefix.

        The generic branch scheduler suppresses already-seen branches globally.
        For directed replay, that is too coarse: a branch seen in a suffix-only
        trace must be solved again after the allocator/prefix bridge is
        confirmed.
        """
        if bid not in self._all_target_bbs:
            return False
        violated_rule = self._violated_must_prefix_for_bb(bid)
        if violated_rule is not None:
            logger.debug(
                "[Plan] Skip forced solve for bid=%s; must-prefix %s is not met",
                bid,
                violated_rule["name"],
            )
            return False
        active_stage = self._active_desired_branch_stage(bid)
        # A repeated switch BB can be "covered" for an earlier case while a
        # later occurrence still needs a different case value.  Keep staged
        # switch targets solvable when their current stage is active.
        if bid in self._covered_bbs and active_stage is None:
            return False
        if not self._needs_directed_solve(bid, result, addr):
            return False
        bridge_score, _ = self._bridge_progress()
        active = self._active_contextual_targets(bridge_score)
        if bid not in active and not self._force_desired_branches:
            return False
        if bid not in active and bid not in self._desired_results:
            return False
        count = self._force_target_solve_count.get(bid, 0)
        if count >= self._force_target_solve_limit:
            return False
        self._force_target_solve_count[bid] = count + 1
        return True

    def _needs_directed_solve(self, bid: int, result, addr=None) -> bool:
        """Avoid solving directed targets that already have desired result.

        Solving always asks the backend for the opposite of the observed
        branch.  For directed policies, forcing a solve when the current result
        is already desired actively creates seeds for the wrong side.
        """
        if bid in self._staged_desired_branches:
            active_stage = self._active_desired_branch_stage(bid)
            if active_stage is None:
                return False
        if bid in self._desired_addrs:
            if addr is None or int(addr) not in self._desired_addrs[bid]:
                return False
        desired_result, desired_addrs = self._active_desired_branch_goal(bid)
        if desired_addrs is not None:
            if addr is None or int(addr) not in desired_addrs:
                return False
        if desired_result is None or result is None:
            return True
        return int(result) != desired_result

    def _bridge_progress(self) -> tuple[int, list[int]]:
        """Return ordered same-execution policy progress.

        `target_bids` describe branches worth solving; `bridge_bids` describe
        BBs that must be present in one execution to preserve object provenance
        across allocation, parser state, and the eventual access.  A trace group
        is complete only when all required bridge BBs, or target BBs if no
        bridge list is supplied, have appeared in the current seed execution.
        """
        completed: list[int] = []
        seen = self._current_trace
        for t in self._traces:
            ordered = t.get("ordered_bridge_bids") or []
            if ordered:
                if self._ordered_prefix_len(ordered) == len(ordered):
                    completed.append(t["priority"])
                    continue
                break
            required = t.get("bridge_bids") or t.get("target_bids") or set()
            if not required:
                continue
            if required.issubset(seen) and all(
                self._branch_goal_replayed(bid) for bid in required
            ):
                completed.append(t["priority"])
                continue
            break
        return len(completed), completed

    def _ordered_prefix_len(self, ordered: list[int]) -> int:
        """Return how much of `ordered` appears as a subsequence in this run."""
        if not ordered:
            return 0
        pos = 0
        for bb in self._current_trace_order:
            if bb == ordered[pos]:
                pos += 1
                if pos == len(ordered):
                    break
        return pos

    def _should_queue_bridge_progress(self) -> tuple[bool, int, list[int]]:
        score, completed = self._bridge_progress()
        if score == 0:
            return False, score, completed
        # Once replay has confirmed a later prefix, old early-prefix variants
        # are usually noise. Keeping them at the front can starve the directed
        # target/UB seeds generated near the final access.
        if score <= self._confirmed_bridge_progress:
            return False, score, completed
        if score > self._best_bridge_progress:
            self._best_bridge_progress = score
            return True, score, completed
        count = self._bridge_retry_count.get(score, 0)
        if count >= self._bridge_retry_limit:
            return False, score, completed
        self._bridge_retry_count[score] = count + 1
        return True, score, completed

    def _latest_bridge_priority(self) -> int:
        """Return the latest policy bridge matched by this execution.

        `_bridge_progress()` is intentionally prefix-strict so it can preserve a
        complete allocation-to-access trace. Late-stage CVE policies also need a
        suffix signal: if the current run already reached a deep bridge such as
        WritePixels, solver results from nearby non-policy branches are usually
        more valuable than generic path-queue entries even when an earlier
        bridge group was not observed in this trace.
        """
        latest = 0
        seen = self._current_trace
        for t in self._traces:
            ordered = t.get("ordered_bridge_bids") or []
            if ordered:
                if self._ordered_prefix_len(ordered) == len(ordered):
                    latest = max(latest, int(t["priority"]))
                continue
            required = t.get("bridge_bids") or t.get("target_bids") or set()
            if required and required.issubset(seen) and all(
                self._branch_goal_replayed(bid) for bid in required
            ):
                latest = max(latest, int(t["priority"]))
        return latest

    def _should_queue_advanced_bridge(self) -> tuple[bool, int]:
        latest = self._latest_bridge_priority()
        if (self._advanced_bridge_min_priority <= 0 or
                latest < self._advanced_bridge_min_priority):
            return False, latest
        count = self._advanced_bridge_retry_count.get(latest, 0)
        if count >= self._advanced_bridge_retry_limit:
            return False, latest
        self._advanced_bridge_retry_count[latest] = count + 1
        return True, latest

    def _active_contextual_targets(self, bridge_score: int) -> set[int]:
        """Targets that can extend the current same-execution bridge prefix."""
        if not self._contextual_targets or bridge_score < 0:
            return set()

        active: set[int] = set()
        start = min(bridge_score, len(self._traces))
        end = min(start + self._contextual_lookahead, len(self._traces))
        for t in self._traces[start:end]:
            active.update(t["target_bids"])
        return active

    def _has_later_target_progress(self, bid: int) -> bool:
        """Return true once a later policy target was reached or covered."""
        try:
            pos = self._target_order.index(bid)
        except ValueError:
            return False
        later_targets = set(self._target_order[pos + 1:])
        return bool(later_targets & (self._covered_bbs | self._visited_target_bbs))

    def _should_retry_target_queue(self, bid: int) -> bool:
        """Keep productive target attempts prioritized until the next target."""
        if bid not in self._all_target_bbs or bid not in self._covered_bbs:
            return False
        if self._has_later_target_progress(bid):
            return False
        count = self._target_retry_count.get(bid, 0)
        if count >= self._target_retry_limit:
            return False
        self._target_retry_count[bid] = count + 1
        return True

    def _is_desired_flip(self, bid: int, original_result, addr=None) -> bool:
        """True if solving this branch should replay with the desired result.

        `append()` is called after SymSan solved the opposite of the currently
        observed branch result.  Therefore a generated seed is directed toward
        desired_result when the current/original result is different from it.
        """
        if bid in self._staged_desired_branches:
            active_stage = self._active_desired_branch_stage(bid)
            if active_stage is None:
                return False
        if bid in self._desired_addrs:
            if addr is None or int(addr) not in self._desired_addrs[bid]:
                return False
        desired_result, desired_addrs = self._active_desired_branch_goal(bid)
        if desired_addrs is not None:
            if addr is None or int(addr) not in desired_addrs:
                return False
        if desired_result is None:
            return True
        if original_result is None:
            return True
        return int(original_result) != desired_result

    def _active_desired_branch_goal(
        self, bid: int
    ) -> tuple[int | None, set[int] | None]:
        """Return the directed branch goal active for this execution prefix."""
        active = self._active_desired_branch_stage(bid)
        if active is not None:
            return active["desired_result"], active["addrs"] or None

        if bid in self._desired_results:
            return self._desired_results[bid], self._desired_addrs.get(bid)
        if bid in self._desired_addrs:
            return None, self._desired_addrs[bid]
        return None, None

    def _active_desired_branch_stage(self, bid: int) -> dict | None:
        """Return the active staged branch goal, if any."""
        stages = self._staged_desired_branches.get(bid)
        if not stages:
            return None
        active = None
        for stage in stages:
            ordered = stage["after_ordered"]
            if ordered and not set(ordered).issubset(self._current_trace):
                continue
            # Stages are policy-ordered. Later matching stages represent later
            # occurrences of the same switch BB and must override earlier cases.
            active = stage
        if active is not None:
            return active
        # No stage is active yet, so do not solve this repeated switch.
        return None

    def _apply_staged_value_override(self, seed: Seed, bid: int, addr) -> None:
        """Rewrite a switch-model byte to the exact case requested by policy.

        Fast switch solving may choose a nearby value that flips the comparison
        but does not enter the intended switch case. When a staged policy gives
        an exact case value, apply it to the byte changed by this solve.
        """
        stage = self._active_desired_branch_stage(bid)
        if stage is None or stage.get("value") is None:
            return
        addrs = stage.get("addrs") or set()
        if addrs and (addr is None or int(addr) not in addrs):
            return
        value = int(stage["value"]) & 0xff
        changed: list[tuple[int, int, int]] = []
        max_objs = max(len(self._current_seed.objects), len(seed.objects))
        for obj_id in range(max_objs):
            before = (
                self._current_seed.objects[obj_id]
                if obj_id < len(self._current_seed.objects) else None
            )
            after = seed.objects[obj_id] if obj_id < len(seed.objects) else None
            if after is None:
                continue
            before_value = before.value if before is not None else []
            for off, byte in enumerate(after.value):
                old = before_value[off] if off < len(before_value) else b"\x00"
                if byte != old:
                    changed.append((obj_id, off, byte[0]))
        if len(changed) != 1:
            logger.debug(
                "[Plan] Staged value override skipped for bid=%s addr=%s: "
                "%s changed bytes",
                bid,
                addr,
                len(changed),
            )
            return
        obj_id, off, old_value = changed[0]
        # A repeated switch BB often emits one candidate seed per switch case
        # before any later stage has replayed.  Do not collapse those useful
        # candidates back to the first active stage; keep exact values that are
        # already requested by any stage for this BB.
        stage_values = {
            int(s["value"]) & 0xff
            for s in self._staged_desired_branches.get(bid, [])
            if s.get("value") is not None
        }
        if len(stage_values) > 1 and old_value in stage_values:
            logger.critical(
                "[Plan] Staged value override kept bid=%s addr=%s: "
                "obj[%s][%s] already 0x%02x",
                bid,
                addr,
                obj_id,
                off,
                old_value,
            )
            return
        seed.set_byte(obj_id, off, value)
        logger.critical(
            "[Plan] Staged value override bid=%s addr=%s: "
            "obj[%s][%s] 0x%02x -> 0x%02x",
            bid,
            addr,
            obj_id,
            off,
            old_value,
            value,
        )

    def _should_queue_contextual_target(
        self, bid: int, bridge_score: int
    ) -> tuple[bool, set[int]]:
        """Queue next-step policy targets even if covered in another context."""
        active = self._active_contextual_targets(bridge_score)
        if not active or bid not in active:
            return False, active
        # Do not keep spending target-queue priority on an earlier contextual
        # gate once a later policy target has already appeared in any replay.
        # This prevents late-stage runs from cycling on Decode/LZW gates after
        # they have reached the actual checked access.
        if self._has_later_target_progress(bid):
            return False, active
        return True, active

    def _violated_must_prefix(self) -> dict | None:
        """Return the violated prefix rule for the current execution, if any."""
        return self._violated_must_prefix_for_seen(self._current_trace)

    def _violated_must_prefix_for_bb(self, bb_id: int) -> dict | None:
        """Return the prefix rule this BB would violate if recorded."""
        if not self._must_prefix_rules:
            return None
        projected = set(self._current_trace)
        projected.add(int(bb_id))
        return self._violated_must_prefix_for_seen(projected)

    def _violated_must_prefix_for_seen(self, seen: set[int]) -> dict | None:
        """Return the violated prefix rule for a projected execution trace."""
        if not self._must_prefix_rules:
            return None
        for rule in self._must_prefix_rules:
            if not rule["before_bbs"].intersection(seen):
                continue
            if rule["required_bbs"].issubset(seen):
                continue
            return rule
        return None

    # ------------------------------------------------------------------
    # Coverage queries
    # ------------------------------------------------------------------

    def _uncovered_traces(self) -> list[dict]:
        """Traces with at least one uncovered target BB."""
        return [
            t for t in self._traces
            if t["target_bids"] and not t["target_bids"].issubset(self._covered_bbs)
        ]

    def _all_covered(self) -> bool:
        """True when every target BB across all traces has been covered."""
        if not self._all_target_bbs:
            return False
        return self._all_target_bbs.issubset(self._covered_bbs)

    # ------------------------------------------------------------------
    # Scheduler interface
    # ------------------------------------------------------------------

    def is_done(self) -> bool:
        if self._all_covered():
            total_q = (len(self._direct_queue) +
                       len(self._target_queue) +
                       len(self._explore_queue) +
                       len(self._path_queue))
            if self._drain_after_covered and total_q > 0:
                logger.info(
                    f"[Plan] All target branches covered; draining queued "
                    f"seeds ({total_q} remaining)"
                )
                return False
            logger.info("[Plan] All target branches covered")
            return True
        if self._counter >= self._budget:
            logger.info(f"[Plan] Budget exhausted: {self._counter}/{self._budget}")
            return True
        # Infeasible detection: target BB was visited (BB_TYPE) but branch
        # was never symbolic (no COND_TYPE) → can't be flipped.
        # Only declare done when queues are also empty: enqueued seeds may
        # explore deeper paths (e.g. the CVE trigger) even if some target BBs
        # are concretely unreachable.
        uncovered = self._all_target_bbs - self._covered_bbs
        if uncovered and uncovered.issubset(self._visited_target_bbs):
            total_q = (len(self._direct_queue) +
                       len(self._target_queue) +
                       len(self._explore_queue) +
                       len(self._path_queue))
            if total_q == 0:
                logger.info(
                    f"[Plan] Remaining targets {sorted(uncovered)} are infeasible "
                    f"(visited but never symbolic) and queues are empty"
                )
                return True
        return False

    def __next__(self) -> Seed:
        if self.is_done():
            self._print_summary()
            raise StopIteration

        if self._counter > 0 and self._counter % 50 == 0:
            self._print_status()

        # Drain exact directed branch flips before broader contextual target
        # seeds.  Otherwise an ordered trace can be starved by later generic
        # target candidates that keep getting inserted at the front.
        for name, q in [("direct", self._direct_queue),
                         ("target", self._target_queue),
                         ("explore", self._explore_queue),
                         ("path", self._path_queue)]:
            if q:
                self._counter += 1
                seed = q.pop(0)
                self._current_trace.clear()
                self._current_trace_order.clear()
                self._last_bb_id = None
                self._current_branch_results.clear()
                self._active_loop_threshold = 0
                self._current_prefix_abort_rule = None
                self._current_seed = seed.clone()
                self._pipe.send(seed.to_ticket())
                logger.debug(
                    f"[Plan] Seed from {name} queue "
                    f"(d:{len(self._direct_queue)} "
                    f"t:{len(self._target_queue)} "
                    f"e:{len(self._explore_queue)} "
                    f"p:{len(self._path_queue)})"
                )
                return seed

        # Cold start
        if self._counter == 0:
            self._counter += 1
            ticket = UcsanTicket()
            ticket.instance_id = 0
            ticket.session_id = 0
            ticket.msg_type = 1
            ticket.payload_size = 0
            self._current_trace.clear()
            self._current_trace_order.clear()
            self._last_bb_id = None
            self._current_branch_results.clear()
            self._active_loop_threshold = 0
            self._current_prefix_abort_rule = None
            self._current_seed = Seed()
            logger.info("[Plan] Cold start")
            self._pipe.send(ticket)
            return Seed()

        # Queues exhausted
        self._print_summary()
        raise StopIteration

    def append(self, seed: Seed, **kwargs) -> None:
        bid = kwargs.get("bid", 0)
        original_result = kwargs.get("result")
        addr = kwargs.get("addr")
        violated_rule = self._violated_must_prefix()
        if violated_rule is not None:
            name = violated_rule["name"]
            self._must_prefix_drop_count += 1
            self._must_prefix_drop_by_rule[name] = (
                self._must_prefix_drop_by_rule.get(name, 0) + 1
            )
            if self._must_prefix_drop_by_rule[name] <= 10:
                logger.info(
                    f"[Plan] Seed dropped (must-prefix {name}: "
                    f"required={sorted(violated_rule['required_bbs'])}, "
                    f"before={sorted(violated_rule['before_bbs'])}, "
                    f"trace={sorted(self._current_trace)})"
                )
            elif self._must_prefix_drop_by_rule[name] == 11:
                logger.info(
                    f"[Plan] Further must-prefix drops for {name} suppressed"
                )
            return

        self._apply_staged_value_override(seed, bid, addr)

        digest = seed.digest().hexdigest()
        if digest in self._seeds_hash:
            return
        self._seeds_hash.add(digest)

        # Track candidate coverage.  With replay confirmation enabled, a solved
        # branch only queues a candidate; coverage is committed when the child
        # replay reaches the policy bridge for that stage.
        is_desired_flip = self._is_desired_flip(bid, original_result, addr)
        is_target_flip = (
            bid in self._all_target_bbs and
            bid not in self._covered_bbs and
            is_desired_flip
        )
        is_target_retry = is_desired_flip and self._should_retry_target_queue(bid)
        if is_target_flip and not self._confirm_targets_by_replay:
            self._covered_bbs.add(bid)
            if bid in self._desired_results:
                logger.critical(
                    f"[Plan] Target branch {bid} directed toward "
                    f"result={self._desired_results[bid]}! "
                    f"({len(self._covered_bbs)}/{len(self._all_target_bbs)})"
                )
            else:
                logger.critical(
                    f"[Plan] Target branch {bid} flipped! "
                    f"({len(self._covered_bbs)}/{len(self._all_target_bbs)})"
                )
        elif is_target_flip:
            if bid in self._desired_results:
                logger.critical(
                    f"[Plan] Target branch {bid} directed toward "
                    f"result={self._desired_results[bid]}; awaiting replay "
                    f"bridge confirmation"
                )
            else:
                logger.critical(
                    f"[Plan] Target branch {bid} flipped; awaiting replay "
                    f"bridge confirmation"
                )

        should_queue_bridge, bridge_score, bridge_completed = self._should_queue_bridge_progress()
        should_queue_advanced, advanced_priority = self._should_queue_advanced_bridge()
        is_contextual_target, active_targets = self._should_queue_contextual_target(
            bid, bridge_score
        )
        is_support_bid = self._is_support_bid_after_bridge(bid, bridge_score)

        # Classification:
        # 1. This seed flips a target branch or extends the ordered BB bridge
        #    chain in the current execution → highest priority.
        if (is_target_flip or is_target_retry or is_contextual_target or
                should_queue_bridge or should_queue_advanced or is_support_bid):
            use_direct_queue = (
                (is_target_flip or is_target_retry) and
                (not self._direct_bids or bid in self._direct_bids)
            )
            if use_direct_queue:
                self._direct_queue.insert(0, seed)
            elif is_target_flip or is_target_retry:
                self._target_queue.append(seed)
            elif is_contextual_target:
                self._target_queue.append(seed)
            elif (should_queue_advanced and
                  not (is_target_flip or is_target_retry or is_contextual_target)):
                self._target_queue.insert(0, seed)
            elif is_support_bid:
                self._target_queue.append(seed)
            else:
                self._target_queue.append(seed)
            if is_target_flip:
                logger.info(
                    f"[Plan] Seed → direct queue "
                    f"(flips target {bid}) @{len(self._direct_queue)}"
                )
            elif is_target_retry:
                logger.info(
                    f"[Plan] Seed → target queue "
                    f"(retries target {bid}, "
                    f"{self._target_retry_count.get(bid, 0)}/"
                    f"{self._target_retry_limit}) @{len(self._direct_queue)}"
                )
            elif is_contextual_target:
                logger.info(
                    f"[Plan] Seed → target queue "
                    f"(contextual target {bid}, bridge {bridge_score}, "
                    f"active={sorted(active_targets)}) @{len(self._target_queue)}"
                )
            elif should_queue_bridge:
                logger.info(
                    f"[Plan] Seed → target queue "
                    f"(bridge progress {bridge_score}, "
                    f"completed P{bridge_completed}) "
                    f"@{len(self._target_queue)}"
                )
            elif should_queue_advanced:
                logger.info(
                    f"[Plan] Seed → target queue "
                    f"(advanced bridge P{advanced_priority}, "
                    f"{self._advanced_bridge_retry_count.get(advanced_priority, 0)}/"
                    f"{self._advanced_bridge_retry_limit}) "
                    f"@{len(self._target_queue)}"
                )
            elif is_support_bid:
                logger.info(
                    f"[Plan] Seed → target queue "
                    f"(support bid {bid} after bridge {bridge_score}) "
                    f"@{len(self._target_queue)}"
                )
        elif (self._drop_non_policy_after_bridge and
              bridge_score >= self._drop_non_policy_min_bridge):
            logger.debug(
                f"[Plan] Seed dropped "
                f"(non-policy bid {bid} after bridge {bridge_score}, "
                f"active={sorted(active_targets)})"
            )
        # 2. New branch ID → exploration
        elif bid not in self._seen_bids:
            # Deprioritize if parent trace was dominated by depri BBs
            if self._current_trace:
                depri_hits = self._current_trace & self._depri_bbs
                if len(depri_hits) > len(self._current_trace) * 0.5:
                    path_limit = max(50, len(self._seen_bids))
                    if len(self._path_queue) < path_limit:
                        self._path_queue.append(seed)
                        logger.debug(
                            f"[Plan] Seed → path queue "
                            f"(depri-dominated) @{len(self._path_queue)}"
                        )
                else:
                    self._explore_queue.append(seed)
                    logger.debug(
                        f"[Plan] Seed → explore queue "
                        f"(new bid {bid}) @{len(self._explore_queue)}"
                    )
            else:
                self._explore_queue.append(seed)
                logger.debug(
                    f"[Plan] Seed → explore queue "
                    f"(new bid {bid}) @{len(self._explore_queue)}"
                )
        # 3. Everything else → path queue (bounded)
        else:
            path_limit = (
                self._path_queue_limit
                if self._path_queue_limit > 0
                else max(100, len(self._seen_bids) * 2)
            )
            if len(self._path_queue) < path_limit:
                self._path_queue.append(seed)
                logger.debug(f"[Plan] Seed → path queue @{len(self._path_queue)}")
            else:
                logger.debug(
                    f"[Plan] Seed dropped (path queue full: "
                    f"{len(self._path_queue)}/{path_limit})"
                )

        self._seen_bids.add(bid)

        if self._save_seeds:
            fname = f"seeds/seed_{time()}.pickle"
            with open(fname, "wb") as f:
                pickle.dump([seed], f)

    # ------------------------------------------------------------------
    # Reporting
    # ------------------------------------------------------------------

    def _print_status(self) -> None:
        elapsed = time() - self._starttime
        rate = self._counter / elapsed if elapsed > 0 else 0
        uncov = self._all_target_bbs - self._covered_bbs
        total_q = (len(self._direct_queue) +
                   len(self._target_queue) +
                   len(self._explore_queue) +
                   len(self._path_queue))
        logger.info(
            f"[Plan] seeds={self._counter}/{self._budget}, "
            f"bb_coverage={len(self._covered_bbs)}/{len(self._all_target_bbs)}, "
            f"bridge={self._confirmed_bridge_progress}/{len(self._traces)} "
            f"(queued={self._best_bridge_progress}), "
            f"uncovered={sorted(uncov)}, "
            f"queued={total_q}, direct={len(self._direct_queue)}, "
            f"rate={rate:.1f}/s"
        )

    def _print_summary(self) -> None:
        elapsed = time() - self._starttime
        logger.critical(f"[Plan] Done: {self._counter} seeds in {elapsed:.1f}s")
        logger.critical(
            f"[Plan] BB coverage: "
            f"{len(self._covered_bbs)}/{len(self._all_target_bbs)}"
        )
        for t in self._traces:
            covered = t["target_bids"] & self._covered_bbs
            total = t["target_bids"]
            status = "COVERED" if total.issubset(self._covered_bbs) else "MISSED"
            logger.critical(
                f"[Plan]   [{status}] P{t['priority']}: {t['goal']} "
                f"({len(covered)}/{len(total)} bids)"
            )
        uncov = self._all_target_bbs - self._covered_bbs
        if uncov:
            logger.critical(f"[Plan]   Uncovered BBs: {sorted(uncov)}")
        if self._must_prefix_rules:
            logger.critical(
                f"[Plan] Must-prefix dropped seeds: "
                f"{self._must_prefix_drop_count} "
                f"{self._must_prefix_drop_by_rule}; "
                f"aborted executions: {self._must_prefix_abort_count}"
            )

    def stat(self) -> None:
        logger.info(f"[Plan] Total {self._counter} seeds processed")

    def loads(self, filename: str) -> None:
        logger.info(f"[Plan] Load seeds from {filename}")
        data = open(filename, "rb").read()
        self._path_queue = pickle.loads(data)
