name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
    paths:
      - '!README.md'


jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install -y llvm-14 clang-14 libc++-14-dev libc++abi-14-dev python3-minimal libgoogle-perftools-dev libboost-container-dev python3-dev

    - name: Cache Z3
      id: cache-z3
      uses: actions/cache@v4
      with:
        path: ~/z3
        key: z3-4.15.4-x64-glibc-2.39

    - name: Install Z3
      run: |
        if [ ! -d ~/z3 ]; then
          wget https://github.com/Z3Prover/z3/releases/download/z3-4.15.4/z3-4.15.4-x64-glibc-2.39.zip
          unzip z3-4.15.4-x64-glibc-2.39.zip
          mv z3-4.15.4-x64-glibc-2.39 ~/z3
        fi
        sudo cp -r ~/z3/bin/* /usr/local/bin/
        sudo cp -r ~/z3/include/* /usr/local/include/
        sudo cp -r ~/z3/lib/* /usr/local/lib/
        sudo ldconfig
    #   run: |
    #     wget https://apt.llvm.org/llvm.sh
    #     chmod +x llvm.sh
    #     sudo ./llvm.sh 12 all

    - name: get aflpp
      uses: actions/checkout@v4
      with:
        repository: AFLplusplus/AFLplusplus
        path: ${{ github.workspace }}/aflpp

    - name: configure
      run: CC=clang-14 CXX=clang++-14 cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install -DAFLPP_PATH=${{ github.workspace }}/aflpp

    - name: build
      run: CC=clang-14 CXX=clang++-14 cmake --build ${{ github.workspace }}/build

    - name: install
      run: CC=clang-14 CXX=clang++-14 cmake --install ${{ github.workspace }}/build

    - name: install lit
      run: pip install lit

    - name: test
      run: lit --verbose tests
      working-directory: ${{ github.workspace }}/build
